# Generated by Django 5.2 on 2025-05-03 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_from_user', models.BooleanField(default=True)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_images/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentioned_in_chats', to='contacts.contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(choices=[('IDENTIFY', 'Identify Person'), ('DETAILS', 'Ask Details'), ('SUGGESTIONS', 'Get Suggestions'), ('OTHER', 'Other Query')], max_length=20)),
                ('resolved', models.BooleanField(default=False)),
                ('chat_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_query', to='chat.chatmessage')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='contacts.contact')),
            ],
        ),
    ]
