# Generated by Django 5.2 on 2025-05-03 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ocr_images/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('taken_date', models.DateTimeField(blank=True, null=True)),
                ('image_type', models.CharField(choices=[('BUSINESS_CARD', 'Business Card'), ('CONFERENCE_AGENDA', 'Conference Agenda'), ('OTHER', 'Other')], default='BUSINESS_CARD', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('processed_text', models.TextField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('processed_date', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_result', to='ocr.ocrimage')),
            ],
        ),
        migrations.CreateModel(
            name='ContactExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_date', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='contacts.contact')),
                ('ocr_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='ocr.ocrresult')),
            ],
        ),
    ]
